# Generated by Django 4.1.5 on 2023-01-29 10:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=200)),
                ('menu', models.CharField(default='', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('forget_password_token', models.CharField(blank=True, max_length=100, null=True)),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registeredhostels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('hostel_number', models.PositiveBigIntegerField(default=0)),
                ('hostel_img', models.ImageField(blank=True, null=True, upload_to='Hostel_img/')),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('address', models.TextField(blank=True, default='', max_length=300, null=True)),
                ('city', models.TextField(default='', max_length=100)),
                ('Total_rooms', models.PositiveIntegerField(default=0)),
                ('Available_rooms', models.PositiveIntegerField(default=0)),
                ('One_bed_rooms', models.PositiveIntegerField(default=0)),
                ('Onebed_per_seat_price', models.PositiveIntegerField(default=0)),
                ('Two_bed_rooms', models.PositiveIntegerField(default=0)),
                ('Two_bed_per_seat_price', models.PositiveIntegerField(default=0)),
                ('Three_bed_rooms', models.PositiveIntegerField(default=0)),
                ('Three_bed_per_seat_price', models.PositiveIntegerField(default=0)),
                ('Four_bed_rooms', models.PositiveIntegerField(default=0)),
                ('Four_bed_per_seat_price', models.PositiveIntegerField(default=0)),
                ('Description', models.TextField(default='')),
                ('is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.CharField(max_length=100)),
                ('seat', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Seat_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seat_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Conform', 'Conform'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('seat_type', models.CharField(choices=[('one bed', 'one bed'), ('Two bed', 'Two bed'), ('Three bed', 'Three bed'), ('Four bed', 'Four bed')], max_length=200, null=True)),
                ('Booked_date', models.DateField(default=django.utils.timezone.now)),
                ('Seat_apply_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hostel_app.customer')),
                ('hostel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Hostel_app.registeredhostels')),
            ],
        ),
    ]
